stages:
  - build
  - unit_test
  - coverage
  

cache:
  paths:
  - build-OPTIM/
  - test-results/coverage/html 
compile:
  stage: build
  script:
    - rm -rf build-OPTIM
    - mkdir build-OPTIM 
    - cd build-OPTIM 
    - cmake3 -DCMAKE_BUILD_TYPE=DEBUG ..
    - make -j12

run_unit_tests:
  stage: unit_test
  script:
    - cd build-OPTIM/test
    - ./run_tests
    - mkdir test-results


coverage:
  stage: coverage
  script:
    - mv build-OPTIM build
    - pwd
    - ls
    - ./runCoverage.sh

  artifacts:
    paths:
    - coverage/html 


    
 
  

