version: 2.1

commands:
  set_up_unit_test_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Run SETUP
          command: sudo ./setup.sh -gtest
      - run:
          name: Install LCOV
          command: apt update && sudo apt install -y lcov
  set_up_production_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Run SETUP
          command: ./setup.sh
  set_up_regression_test_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing PYHTON
          command: 'apt-get update && sudo apt install -y python3'
      - run:
          name: Run SETUP
          command: ./setup.sh
  build_optim:
    steps:
      - run:
          name: Build Optim
          command: 'mkdir build-Optim && cd build-Optim && cmake -DCMAKE_BUILD_TYPE=Debug .. && make'
  run_unit_tests:
    steps:
      - run:
          name: Run unit tests
          command: cd test && mkdir test-results && ./run_tests --gtest_output="xml:./test-results/results.xml"
      - store_test_results:
          path: test-results
      - run:
          name: Run LCOV
          command: |
            lcov --capture --directory . --output-file ./test-results/coverage.info
            lcov -r "./test-results/coverage.info" "/tinyXML/*" "*/logger/*" "boost" "*/boost/*" "*/test/*" "*/armadillo_bits/*" "*/include/*" "*/gtest/*" "*/c++/*" "*/Core/*" "/usr/" "*/gcc/*" -o "./test-results/coverage-filtered.info"
            genhtml ./test-results/coverage-filtered.info --output-directory coverage
      - store_artifacts:
          path: coverage
executors:
  docker-bionic:
    docker:
      - image: "ubuntu:bionic"

jobs:
  unit_tests:
    executor: docker-bionic
    steps:
      - set_up_unit_test_environment
      - run_unit_tests
workflows:
  build-and-run-tests:
    jobs:
      - unit_tests
