MOTIONS: inner_products Class Reference
inner_products Class Reference
Public Member Functions
double L2_inner_product (arma::mat m1, arma::mat m2)
double H1_inner_product (arma::mat m1, arma::mat m2)
double H2_inner_product (arma::mat m1, arma::mat m2)
Public Member Functions inherited from abstract_controller
data_provider getData_provider_optim () const
void setData_provider_optim (const data_provider &value)
Member Function Documentation
H1_inner_product()
double inner_products::H1_inner_product (arma::mat m1, arma::mat m2)
L2 part
References equation_solving_controller::D1_second_order().
H2_inner_product()
double inner_products::H2_inner_product (arma::mat m1, arma::mat m2)
L2 and H1 part
References H1_inner_product(), and equation_solving_controller::Laplacian_3D().
The documentation for this class was generated from the following files:
/home/jan/Promotion_linuxPC/Optim_VSTRAP/src/tools/inner_products.h
/home/jan/Promotion_linuxPC/Optim_VSTRAP/src/tools/inner_products.cpp