MOTIONS: optim_controller Class Reference
optim_controller Class Reference
The optim_controller class provides methods for starting and the optimizer and visualizing the results.
#include <optim_controller.h>
Public Member Functions
int start_optimizer (int argc, const char **argv)
start_optimizer reads in the command line command and starts the optimizer
Public Member Functions inherited from abstract_controller
data_provider getData_provider_optim () const
void setData_provider_optim (const data_provider &value)
Static Public Member Functions
static int main_optimization_algorithm (const char *input_xml_path)
main_optimization_algorithm is the core optimization algorithm which uses the paramteres defined in the input file for the optimizer
static arma::mat start_with_zero_control (const char *input_xml_path)
start_with_zero_control deletes the whole folder containing the files from the last optimization run, creates a new initial guess that is zero everywhere
static arma::mat start_with_given_control (const char *input_xml_path)
start_with_given_control delets only the txt and csv files and starts with the control that is currently in the results folder
static int generate_input_files (const char *input_xml_path)
generate_input_files starts the generation of the VSTRAP input files for forward, backward and adjoint_creation
static int post_processing_convergence (data_provider provider)
post_processing_convergence starts the python post-processing method
static int visualize_control (data_provider provider)
visualize_control starts the python method for visualizing the control in three dimensions
static int paraview_plot_forward (data_provider provider)
paraview_plot_forward starts the python routine for displaying the evolution of the solution to the forward equation using a python script for paraview
Detailed Description
The optim_controller class provides methods for starting and the optimizer and visualizing the results.
Member Function Documentation
generate_input_files()
int optim_controller::generate_input_files (const char * input_xml_path) static
generate_input_files starts the generation of the VSTRAP input files for forward, backward and adjoint_creation
Parameters
input_xml_path
Returns
main_optimization_algorithm()
int optim_controller::main_optimization_algorithm (const char * input_xml_path) static
main_optimization_algorithm is the core optimization algorithm which uses the paramteres defined in the input file for the optimizer
Parameters
input_xml_path
Returns
START OPTIMIZATION ITERATION
first stepsize guess, scaled with norm of gradient
References pdf_controller::assemblingMultiDim_parallel(), pdf_controller::calculate_wasserstein_metric(), gradient_calculator::calculateGradient_forceControl_space_Hm(), gradient_calculator::calculateGradient_forceControl_space_Hm_plasma(), generate_input_files(), stepdirection_controller::get_stepdirection(), paraview_plot_forward(), post_processing_convergence(), start_with_given_control(), start_with_zero_control(), visualize_control(), and output_control_update::writeControl_XML().
paraview_plot_forward()
int optim_controller::paraview_plot_forward (data_provider provider) static
paraview_plot_forward starts the python routine for displaying the evolution of the solution to the forward equation using a python script for paraview
Parameters
provider
Returns
post_processing_convergence()
int optim_controller::post_processing_convergence (data_provider provider) static
post_processing_convergence starts the python post-processing method
Parameters
provider
Returns
start_optimizer()
int optim_controller::start_optimizer (int argc, const char ** argv)
start_optimizer reads in the command line command and starts the optimizer
Parameters
argc
argv
Returns
References main_optimization_algorithm().
start_with_given_control()
arma::mat optim_controller::start_with_given_control (const char * input_xml_path) static
start_with_given_control delets only the txt and csv files and starts with the control that is currently in the results folder
Parameters
input_xml_path
Returns
References input::readControl(), and output_control_update::writeControl_XML().
start_with_zero_control()
arma::mat optim_controller::start_with_zero_control (const char * input_xml_path) static
start_with_zero_control deletes the whole folder containing the files from the last optimization run, creates a new initial guess that is zero everywhere
Parameters
input_xml_path
Returns
References output_control_update::writeControl_XML().
visualize_control()
int optim_controller::visualize_control (data_provider provider) static
visualize_control starts the python method for visualizing the control in three dimensions
Parameters
provider
Returns
The documentation for this class was generated from the following files:
/home/jan/Promotion_linuxPC/Optim_VSTRAP/src/controller/optim_controller.h
/home/jan/Promotion_linuxPC/Optim_VSTRAP/src/controller/optim_controller.cpp